### ISSUE TITLE
Using at.rsi with dplyr's mutate and across

### ISSUE THREAD

**Issue by antunderwood** [msberends/AMR#11]
I have a line to calculate RSI values in a df as follows
```
rsi_data <- mic_amr_data %>% dplyr::mutate_at(vars(-c(id,Species,mo)), as.rsi, mo = .$mo, guideline = 'EUCAST')
```

If I try with the new across() function from dplyr 1.0
```
rsi_data <- mic_amr_data %>% dplyr::mutate(across(-c(id,Species,mo), as.rsi, mo = .$mo, guideline = 'EUCAST'))
```
every column is interpreted as `col` which the package thinks is COLISTIN

**Comment by msberends** [comment]
Can you share some data, like the first 10 rows without patient details?

**Comment by antunderwood** [comment]
A sample of 100 isolates can be found [here](https://gist.github.com/aunderwo/edd0a12bacabc14b6a52f46ae2e99459)

The output from using across

```
> sample %>% dplyr::mutate(across(-c(mo), as.rsi, mo = .$mo, guideline = 'EUCAST'))
=> Interpreting MIC values of `col` (COL, colistin) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `col` (COL, colistin) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `col` (COL, colistin) using guideline EUCAST 2020 ... OK.
......
```
The output from using mutate_at
```
dplyr::mutate_at(vars(-c(mo)), as.rsi, mo = .$mo, guideline = 'EUCAST')
=> Interpreting MIC values of `AMC` (amoxicillin/clavulanic acid) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `AMK` (amikacin) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `AMP` (ampicillin) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `ATM` (aztreonam) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `AZM` (azithromycin) using guideline EUCAST 2020 ... OK.
=> Interpreting MIC values of `CAZ` (ceftazidime) using guideline EUCAST 2020 ... OK.
.......
```

**Comment by msberends** [comment]
Not sure if I can make `across()` work. It doesn't seem to pass on the variable names of the drugs, so I'm not sure if I can retrieve the variable names in another way.

I'll look further for other ways. For now, you have two options:

```r
# 1. The one you mentioned
mic_amr_data %>% mutate_at(vars(-mo), as.rsi, mo = .$mo, guideline = 'EUCAST')

# 2. The super short version that automatically determines the mo and ab columns
mic_amr_data %>% as.rsi(guideline = 'EUCAST')
```

Since EUCAST is the default guideline, you can omit that argument as well.

**Comment by antunderwood** [comment]
Is it possible to use the current column param?

https://dplyr.tidyverse.org/articles/colwise.html#current-column-1

**Comment by msberends** [comment]
YES! Thank you so much!

**Comment by msberends** [comment]
Solved in https://github.com/msberends/AMR/commit/0d9602a6a9f254237ea630e9775fa71cdd5b55d4.

Because of the dplyr function to determine the current column, I was also able to determine the total data set when in a `mutate()` verb. And that's great, because it allows to automatically determine the column with microorganism names or codes. 

So interpreting your data is now as easy as either:

```r
mic_amr_data %>% mutate_if(is.mic, as.rsi)

mic_amr_data %>% mutate(across(where(is.mic), as.rsi))
```

**Comment by msberends** [comment]
I also rewrote the documentation for `as.rsi()`: https://msberends.github.io/AMR/reference/as.rsi.html#details

**Comment by antunderwood** [comment]
Fantastic. Thank you!
