### ISSUE TITLE
how are IE cut-offs used in MIC graphs

### ISSUE THREAD

**Issue by theanita1** [msberends/AMR#119]
Hi Mattjis

For P. aeruginosa and Gentamicin using EUCAST 2022, there are no defined cut-offs, rather it sends you to the MIC distribution database. 

However, in my MIC graph for that same drug/bug combo it appears as such:
![image](https://github.com/msberends/AMR/assets/11519951/921a7956-7ffd-4e49-b566-34325dbe42ae)

I have another MIC graph where there are no cut-offs available (S. aureus and Mupirocin) and the bars are grey
![image](https://github.com/msberends/AMR/assets/11519951/7b0c3241-e99f-4584-a99f-c220c539a77c)

Can you explain what's going on with the P. aero/Gentamicin chart? I've got PKPD turned off in my MIC interpretation

Cheers

**Comment by msberends** [comment]
I will have a look at this. Might be due to species groups that WHONET introduced which we use. I'll get back to you!

**Comment by msberends** [comment]
That's because PK/PD rules are (or actually: were) always used for getting the interpretations in plots. That should be settable by the user , so that's now fixed, all plotting functions gained the `include_PKPD` argument that `as.sir()` also has. So, if you've set this to FALSE, you will now get this:

<img width="943" alt="image" src="https://github.com/msberends/AMR/assets/31037261/f3414bf9-dbfa-41aa-a50d-cfdb8afdc544">
  
  
  

Moreover, the subtitle will now always contain the reference table from the guideline, like this:

<img width="933" alt="image" src="https://github.com/msberends/AMR/assets/31037261/cfc74c1c-652c-4261-943b-bd928f026d4d">

<img width="945" alt="image" src="https://github.com/msberends/AMR/assets/31037261/0da0da9f-3e04-42f2-a60d-b3f4e4adacee">

**Comment by msberends** [comment]
Still working on some internal tests, it's not on GitHub yet, but will be in a moment :)

**Comment by msberends** [comment]
All is right it seems!

**Comment by theanita1** [comment]
Thanks for the update, I'm not sure it's working for me, but that's because all my Pseudomonas charts are now interpreting as Acinetobacter? 

![image](https://github.com/msberends/AMR/assets/11519951/9e235380-42e3-44c1-a8bf-eb4b70984324)

autoplot(pseudo_mic$GEN, mo = "Pseudomonas", ab = "Gentamicin", guideline = "EUCAST 2022", include_PKPD = F)

**Comment by msberends** [comment]
Yes, that’s because Pseudomonas  are Coryneform bacteria. According to WHONET, Pseudomonas species are part of that group and should be interpreted as such. I’ll look up the EUCAST guideline today to see if this is right or wrong.

**Comment by msberends** [comment]
Appeared to be the same bug introduced in #108
