### ISSUE TITLE
Question about multiple cut-offs per antibiotic

### ISSUE THREAD

**Issue by andrewjmc** [msberends/AMR#168]
Hi Matthijs and team,

Is AMR setup to handle multiple SIR results for the same antibiotic within a data-frame? (especially relevant with the recent proliferation of distinct cut-offs for amox/co-amox, etc). Can I have two columns for the same antibiotic with different indications? How would `antibiogram` handle this?

Also, although I know that `as.sir` accepts a `UTI` parameter, so distinct SIR results can be generated, but I can't see additional parameters to cover further different indications.

Thanks!

Andrew

**Comment by msberends** [comment]
I tried my new best friend for this question 😛 Just trained a manual GPT to contain all package knowledge, see here: <https://chatgpt.com/g/g-M4UNLwFi5-amr-for-r-assistant>.


Its response:

![image](https://github.com/user-attachments/assets/f061fbc2-7284-40e5-a164-61efa41ada8e)

And it's completely right! But you still can, by *not* transforming the antibiotic columns:

```r
fake_data <- data.frame(mo = "E. coli", amoxicillin_uti = random_sir(100), amoxicillin_other = random_sir(100))

# Default, converts AB columns to their official code, then to the output the user sets (defaults to `"name"` for the official name)
fake_data |> antibiogram()
#> ℹ Using column 'mo' as input for col_mo.
#> ℹ Returning previously coerced values for "E. coli". Run mo_reset_session() to reset this. This note will be shown once per session for this input.
#> ℹ More than one result was found for item 1: amoxicillin and cefalotin
#>   Pathogen  Amoxicillin
#> 1  E. coli 64% (64/100)
#> Warning message:
#> In reshapeWide(data, idvar = idvar, timevar = timevar, varying = varying,  :
#>   multiple rows match for ab=Amoxicillin: first taken

# Now without transforming the antibiotics
fake_data |> antibiogram(ab_transform = NULL)
#> ℹ Using column 'mo' as input for col_mo.
#>   Pathogen amoxicillin_other amoxicillin_uti
#> 1  E. coli      59% (59/100)    66% (66/100)
```

So that does work. Using `as.sir()` on beforehand to get different results based on UTI/non-UTI breakpoints is currently not implemented, because `as.sir()` must use `as.ab()` on the column internally to get the correct breakpoints.

So, that's not implemented as of yet. But you could run the interpretation twice: once on a dataset with a drug like amoxicillin with UTIs and once with amoxicillin without UTIs. Then merge (`cbind()` or `dplyr::bind_cols()`) the data sets and run `antibiogram()` with `ab_transform = NULL`.

**Comment by andrewjmc** [comment]
Hi Mathijs,

Thanks for the very comprehensive answer! For my purposes, your answer is probably best - I hadn't spotted the `ab_transform` parameter of antibiogram! (Nor did ChatGPT, I think).

I'm sure it would require considerable restructuring, but is there any consideration of having SIR columns also incorporate detail on the specific breakpoint applied (where multiple are available) and be handled transparently by antibiogram?

**Comment by msberends** [comment]
That would indeed be a complete restructuring, but I could imagine that we add attributes to each SIR value about its interpretation from a raw value. So that every single SIR value would have the data about how it got from MIC or disk to that value. Great idea for v3.1 for next year 😃

**Comment by theanita1** [comment]
Adding my vote for this to be achieved somehow in the future - there's some abx with systematic infections or meningitis etc
