### ISSUE TITLE
Package removed from CRAN?

### ISSUE THREAD

**Issue by drpturner** [msberends/AMR#35]
I've just tried to reinstall "AMR" into R  (4.0.5, 64bit, Win10 1909) and got the following error:

Warning in install.packages :
  package ‘AMR’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Heading over to https://cran.r-project.org/web/packages/AMR/index.html, I see this:

Package ‘AMR’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2021-05-22 as check problems were not corrected in time.
A summary of the most recent check results can be obtained from the check results archive.
Please use the canonical form https://CRAN.R-project.org/package=AMR to link to this page.

Is a fix coming? It would be such a shame for this incredibly useful package to disappear.

**Comment by msberends** [comment]
Thank you!

Yes, CRAN archived it because of a bug introduced in dplyr 1.0.6: https://github.com/tidyverse/dplyr/issues/5881

Without any notice, CRAN archived our package because some checks failed caused by that bug. We were never updated about this, and upon resubmission of our package, the CRAN administrators are now complaining that our package is too large for frequent updates (despite this argument is not in their policies, so it feels very arbitrary). It’s rather unbelievable and it feels tremendously unrighteous. Unfortunately, we hear more of these kinds of stories about CRAN and even found this outcry: https://github.com/cranchange/cran_change.org/blob/main/letter.md. 

But rest assured, this package will never leave for this silly reason. We also found the R-universe, a CRAN alternative. If we indeed cannot have it on CRAN anymore, we will look for a different way. That could be this:

```r
install.packages("AMR", repos = "https://msberends.r-universe.dev")
```

I will post updates here, so other people can find and follow progress on the matter as well.

**Comment by drpturner** [comment]
Thank you!

**Comment by llrs** [comment]
Hi @msberends I found your story, following some comments. Sorry it happened.

Would you open an issue on https://github.com/cranchange/cran_histories with more context and quoting the emails you got and when you got them?  The displayed reason of archival is that you didn't correct them on time: "Archived on 2021-05-22 as check problems were not corrected in time."
Alternatively do you mind if I add it? 
Thanks!

**Comment by msberends** [comment]
I ABSOLUTELY will. This really has to stop.

**Comment by msberends** [comment]
CRAN has accepted our next version, we just resubmitted and tried. Now I feel safe to add my story to https://github.com/cranchange/cran_histories.

**Comment by llrs** [comment]
Great! Happy to hear the package is back! 
I would be interested in knowing why you didn't feel safe to add your story before. If you don't feel safe to add a new history about this maybe you can send me a DM on twitter ([@Lluis_Revilla](https://twitter.com/Lluis_Revilla)).

**Comment by msberends** [comment]
No, I’ll will put everything out in the open! I’m a strong defendant of open communication (also think the whole CRAN submission process should be public, including all mail traffic). 

But because it is now so closed and arbitrary, I didn’t want to complain publicly, as it might have led to bad consequences regarding our resubmission. That the saddest part :(

**Comment by msberends** [comment]
See https://github.com/cranchange/cran_histories/discussions/45

**Comment by drpturner** [comment]
Very pleased to see it back on CRAN - thank you
