### ISSUE TITLE
Adding option to ggplot_pca for angle of vector labels

### ISSUE THREAD

**Issue by a2freema** [msberends/AMR#4]
Hello:
I was happy to see that you have updated the ggbiplot function. I had parameterized some of the colors as well for personal use, but I am new to github and coding.

One thing I had added that you might want to consider is the option to angle or not angle the vector labels. I prefer the text to be parallel for figures, personally.

Let me know if you need help!

**Comment by msberends** [comment]
Hey thanks!

Sure, that’s a nice addition. And you’re right in time, since we’re almost releasing a new version. So I’ll implement it next week and you will hopefully be able to update the package by 2-3 weeks from now. 

I’ll let you know when I added your option, and then you’re of course also welcome to test the beta version using:
```r
remotes::install_github("msberends/AMR")
```

I’ll keep you posted!

**Comment by msberends** [comment]
This was added in https://github.com/msberends/AMR/commit/1b65d76cfb7f9bc0e800f6ec3fce32f89f698868#diff-556b8085269250ea0a72def2f90132b4, that can be downloaded with `remotes::install_github("msberends/AMR")`.

I will release a new version by the end of this week to CRAN, so keep posted!

Thanks again.

**Comment by msberends** [comment]
### Fix released to official R repository
Just a small notice: we released a new software version, containing the fix to this issue. Please update your version using either the user interface of your software, or by running:
```r
install.packages("AMR")
```
