### ISSUE TITLE
Update of candida taxonomy

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#45]
Hai Matthijs

will you be including the (rather extensive) update on the candida taxonomy?

https://pubmed.ncbi.nlm.nih.gov/33028600/

Greeting
Rogier

**Comment by msberends** [comment]
Thanks for bringing this up!

We will definitely incorporate this, as soon as it is published by an authoritative journal on taxonomy, which the Journal of Clinical Microbiology is not. The `AMR` package only includes taxonomic names that were formally published in taxonomic journals. I’ll explain a bit how this works. 

Taxonomic name changes come in at least two stages: explaining the taxonomic importance and consequences, and explaining any other importance and/or consequence (such as clinical ones). A methodological taxonomic paper will probably follow from these authors, which will then be peer-reviewed by taxonomists. This might take some years though.

A great example is the renaming of some strains of non-aureus staphylococci into *Staphylococcus pettenkoferi*. It was described for the first time in Diagnostic Microbiology and Infectious Disease in 2002 ([link](https://doi.org/10.1016/s0732-8893(02)00399-1)), but it was not before 2007 that a publication in the International Journal of Systematic and Evolutionary Microbiology (IJSEM) followed ([link](https://doi.org/10.1099/ijs.0.64381-0)). As a consequence:

```r
mo_year("S. pettenkoferi")
#> [1] 2007
```

It does not return 2002 (the year of the first paper), but 2007 (the year of the formal taxonomic publication). For the *Candida* paper you mentioned this will be the same. Although theoretically, the taxonomic paper might get rejected and never published, as it could be the their taxonomic renaming makes sense clinically but not taxonomically. We have to await that.

We don’t incorporate manual changes, we rely on external, reliable sources.

**Comment by ghost** [comment]
Thanks for the info. I am not an expert on taxonomy. I think that this nomenclature will catch on due to its clinical relevance (c glabrata and c krusei). But i see your point. The automatic determination systems (Maldi Bruker) are going to use it. I suspect that the average user of AMR does not want to wait 5 years.... 😀

**Comment by msberends** [comment]
I’m a specialist neither, but learned a lot about taxonomy for the development of our package - we wanted it to be as solid as it could possibly be, also with regard to the taxonomy of microorganisms. 

But wow, I’m a bit shocked that Bruker will implement it anyway. Are you sure? It’s not quite the best practice to change taxonomy based on one paper, that would lead to a huge fragmentation of different ‘truths’ if everybody would do that. 

Let’s see where this goes :)

**Comment by msberends** [comment]
I’ll reopen this since we now rely on GBIF and there’s increasingly more known/debated about this. 

For example, https://twitter.com/jgpharmd/status/1573354689437241344

Summary paper Borman et al 2021, JCM: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8111128/

And their erratum: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8092722/

**Comment by msberends** [comment]
This update is not part of the current ‘backbone taxonomy’ of GBIF 2022 (doi [10.15468/39omei](https://doi.org/10.15468/39omei)). 

This will be added automatically if GBIF has incorporated it using [our new automated script](https://github.com/msberends/AMR/blob/main/data-raw/reproduction_of_microorganisms.R), but since they update their taxonomy yearly it will not happen before the end of 2023...
